receivers:
  awsecscontainermetrics:
      collection_interval: 30s
  awsxray:
    transport: udp
  prometheus:
    config:
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
      scrape_configs:
      - job_name: "envoy"
        metrics_path: "/stats/prometheus"
        static_configs:
        - targets: [ "127.0.0.1:9901" ]

processors:
  filter:
    metrics:
      include:
        match_type: strict
        metric_names:
          - ecs.task.memory.utilized
          - ecs.task.memory.reserved
          - ecs.task.cpu.utilized
          - ecs.task.cpu.reserved
          - ecs.task.network.rate.rx
          - ecs.task.network.rate.tx
          - ecs.task.storage.read_bytes
          - ecs.task.storage.write_bytes

  resourcedetection:
    detectors:
      - ecs

  resource:
    attributes:
    - key: aws.log.stream.arns
      action: delete
    - key: aws.log.stream.names
      action: delete
    - key: aws.log.group.arns
      action: delete
    - key: aws.log.group.names
      action: delete
    - key: cloud.provider
      action: delete
    - key: cloud.platform
      action: delete
    - key: cloud.account.id
      action: delete
    - key: cloud.availability_zone
      action: delete
    - key: cloud.region
      action: delete
    - key: aws.ecs.cluster.arn
      action: delete
    - key: aws.ecs.launchtype
      action: delete

exporters:
  awsxray:
    region: eu-west-1
  awsprometheusremotewrite:
    endpoint: "https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/ws-7c462599-e516-4d4b-a177-53d66adb7a25/api/v1/remote_write"
    resource_to_telemetry_conversion:
      enabled: true
    aws_auth:
      region: eu-west-1
      service: aps

service:
  pipelines:
    traces:
      receivers: [awsxray]
      exporters: [awsxray]
#    metrics/ecs:
#      receivers: [awsecscontainermetrics]
#      processors: [resource, filter]
#      exporters: [awsprometheusremotewrite]
    metrics/envoy:
      receivers: [prometheus]
      processors: [resourcedetection, resource]
      exporters: [awsprometheusremotewrite]
